server:
  port: 18010
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取JWT验签公钥请求路径
          jwk-set-uri: 'http://localhost:17010/rsa/publicKey'
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启服务注册和治理
          lower-case-service-id: true #
      routes: #配置路由路径
        - id: blue-admin
          uri: lb://blue-admin
          predicates:
            - Path=/blue-admin/** #路由匹配http://localhost:17010/blue-admin/admin/*转发到http://localhost:16010/admin/*
          filters:
            - StripPrefix=1 #移除前缀一个1单位blue-admin
        - id: blue-auth
          uri: lb://blue-auth
          predicates:
            - Path=/blue-auth/**
          filters:
            - StripPrefix=1
  redis:
    database: 14
    port: 6379
    host: 106.52.218.27
    password: bWb2VY5!0Aih
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/mall-auth/oauth/token"
      - "/mall-auth/rsa/publicKey"
      - "/mall-search/**"
      - "/mall-portal/sso/login"
      - "/mall-portal/sso/register"
      - "/mall-portal/sso/getAuthCode"
      - "/mall-portal/home/**"
      - "/mall-portal/product/**"
      - "/mall-portal/brand/**"
      - "/mall-admin/admin/login"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
